name: vertical
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests>=2.31.0
  - python-dotenv>=1.0.0
  - pandas>=2.2.0
  - matplotlib>=3.8.0
  - scipy>=1.13.0
  - numpy>=1.26.0
  - tqdm>=4.66.0
  - pip
  - jupyter
  - pip:
      - openai
  - tabulate
